[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
fs_permissions = [
    { access = "write", path = "./deployments" }
]

# 测试配置
[fuzz]
runs = 256

# 格式化配置
fmt = "forge fmt"

# 测试配置
[invariant]
runs = 256
depth = 15

# 网络配置
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
local = "${LOCAL_URL}"
mainnet = "https://mainnet.infura.io/v3/ab65659768724710a5009895c32ed59e"

# Etherscan配置
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }